### ISSUE TITLE
error raised during websocket heartbeat after bot run over 10 hours

### ISSUE THREAD

**Issue by cloudyaaron** [TWT233/khl.py#54]
error raised during websocket heartbeat
Traceback (most recent call last):
  File "khl\receiver.py", line 59, in heartbeat
  File "aiohttp\client_ws.py", line 165, in send_json
  File "aiohttp\client_ws.py", line 151, in send_str
  File "aiohttp\http_websocket.py", line 690, in send
  File "aiohttp\http_websocket.py", line 601, in _send_frame
ConnectionResetError: Cannot write to closing transport

**Comment by TWT233** [comment]
the websocket connection is broken

khl websocket is not high availability ensured, try webhook?
