### ISSUE TITLE
No closing quotation

### ISSUE THREAD

**Issue by omoidesu** [TWT233/khl.py#9]
> [INFO] 2021-06-23 15:45:17,652 @ khl.Bot(run): launching
Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Bot._event_handler.<locals>._dispatch_msg() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\khl\bot.py:104> exception=ValueError('No
closing quotation')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\khl\bot.py", line 115, in _dispatch_msg
    await self._cmd_handler(m)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\khl\bot.py", line 89, in _cmd_handler
    (msg, raw_cmd) = parser(msg, self.cmd_prefix)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\khl\parser.py", line 11, in parser
    raw_cmd = shlex.split(msg.content[len(prefix):])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\shlex.py", line 311, in split
    return list(lex)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\shlex.py", line 300, in __next__
    token = self.get_token()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\shlex.py", line 109, in get_token
    raw = self.read_token()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\shlex.py", line 191, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation

@bot.command(name = 'music') 
async def music(msg:TextMsg, *args):

args里如果出现‘则会出现报错

**Comment by TWT233** [comment]
修好了，大概是合着下一个版本一起发（大概是两周吧，俺尽量不鸽）

着急的话可以自己 build 一个版本给用，蛮简单的，拉了源码装好requirements.txt然后`python setup.py sdist bdist_wheel`就行
